services:
  pokemon.service:
    image: ${DOCKER_REGISTRY-}pokemonservice
    ports:
       - "8080:8080"
       - "8081:8081"
    build:
      context: .
      dockerfile: Pokemon.Service/Dockerfile
